sudo: no
language: python
cache: pip
matrix:
  include:
    - python: "2.7"
      env: TOXENV=docs
    - python: "2.7"
      env: TOXENV=flake8
    - python: "2.7"
      env: TOXENV=py27-1.11
    - python: "3.5"
      env: TOXENV=py35-1.11
    - python: "3.5"
      env: TOXENV=py35-2.1
    - python: "3.6"
      env: TOXENV=py36-2.2
      dist: xenial  # For SQLite 3.8.3 or later
    - python: "3.7"
      env: TOXENV=py37-3.0
      dist: xenial  # For Python 3.7
    - python: "3.8"
      env: TOXENV=py38-master
      dist: xenial  # For Python 3.8
  allow_failures:
    - env: TOXENV=py38-master
install:
  - pip install tox
script:
  - tox
