sudo: no
language: python
cache: pip
matrix:
  include:
    - python: "2.7"
      env: TOXENV=docs
    - python: "2.7"
      env: TOXENV=flake8
    - python: "2.7"
      env: TOXENV=py27-1.11
    - python: "3.4"
      env: TOXENV=py34-1.11
    - python: "3.5"
      env: TOXENV=py35-2.1
    - python: "3.6"
      env: TOXENV=py36-2.2
    - python: "3.6"
      env: TOXENV=py36-master
  allow_failures:
    - env: TOXENV=py36-master
install:
  - pip install coveralls tox
script:
  - tox
after_success: coveralls
